name: Deploy Static Files

on:
  push:
    paths:
      - 'brainy-bite/src/main/resources/static/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js (for compatibility)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Check out the code
      uses: actions/checkout@v3

    - name: Copy static files
      run: |
        mkdir -p static-deploy
        cp -r brainy-bite/src/main/resources/static/* static-deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: static-deploy
        publish_branch: gh-pages

